//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Sage.Integration.Northwind.Application.API
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sage.com", IsNullable = false)]
    public partial class CheckHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string userNameField;

        private string passwordField;

        private string companyNameField;

        private string sessionIdField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class Pricing
    {

        private string accountIdField;

        private string orderQuoteIdField;

        private bool isQuoteField;

        private System.DateTime dateOpenedField;

        private string statusField;

        private string currencyField;

        private string pricingListIdField;

        private string consigneeField;

        private string salesReprField;

        private string productFamilyIdField;

        private string productIdField;

        private decimal quantityField;

        private string quotedPriceField;

        private string uomIdField;

        private string lineTypeField;

        private bool doNotRepriceField;

        private string erpLocationField;

        private decimal discountField;

        private decimal discountSumField;

        private string listPriceField;

        private string quotedPriceTotalField;

        private string synchMessageField;

        private string repricingStatusField;

        private decimal taxRateField;

        private decimal discountRateField;

        private decimal taxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OrderQuoteId
        {
            get
            {
                return this.orderQuoteIdField;
            }
            set
            {
                this.orderQuoteIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool IsQuote
        {
            get
            {
                return this.isQuoteField;
            }
            set
            {
                this.isQuoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime DateOpened
        {
            get
            {
                return this.dateOpenedField;
            }
            set
            {
                this.dateOpenedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string PricingListId
        {
            get
            {
                return this.pricingListIdField;
            }
            set
            {
                this.pricingListIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string SalesRepr
        {
            get
            {
                return this.salesReprField;
            }
            set
            {
                this.salesReprField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string ProductFamilyId
        {
            get
            {
                return this.productFamilyIdField;
            }
            set
            {
                this.productFamilyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string QuotedPrice
        {
            get
            {
                return this.quotedPriceField;
            }
            set
            {
                this.quotedPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string UomId
        {
            get
            {
                return this.uomIdField;
            }
            set
            {
                this.uomIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string LineType
        {
            get
            {
                return this.lineTypeField;
            }
            set
            {
                this.lineTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public bool DoNotReprice
        {
            get
            {
                return this.doNotRepriceField;
            }
            set
            {
                this.doNotRepriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string ErpLocation
        {
            get
            {
                return this.erpLocationField;
            }
            set
            {
                this.erpLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public decimal DiscountSum
        {
            get
            {
                return this.discountSumField;
            }
            set
            {
                this.discountSumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string ListPrice
        {
            get
            {
                return this.listPriceField;
            }
            set
            {
                this.listPriceField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string QuotedPriceTotal
        {
            get
            {
                return this.quotedPriceTotalField;
            }
            set
            {
                this.quotedPriceTotalField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string SynchMessage
        {
            get
            {
                return this.synchMessageField;
            }
            set
            {
                this.synchMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string RepricingStatus
        {
            get
            {
                return this.repricingStatusField;
            }
            set
            {
                this.repricingStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public decimal TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public decimal DiscountRate
        {
            get
            {
                return this.discountRateField;
            }
            set
            {
                this.discountRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public decimal Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class ViewRealTimeDataResult
    {

        private System.Xml.XmlNode realTimeDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.Xml.XmlNode RealTimeData
        {
            get
            {
                return this.realTimeDataField;
            }
            set
            {
                this.realTimeDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class OrderFields
    {

        private string nameField;

        private string descendingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Descending
        {
            get
            {
                return this.descendingField;
            }
            set
            {
                this.descendingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class SearchField
    {

        private string nameField;

        private OperatorValue operatorField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public OperatorValue Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public enum OperatorValue
    {

        /// <remarks/>
        Equals,

        /// <remarks/>
        NotEquals,

        /// <remarks/>
        GreaterThanEquals,

        /// <remarks/>
        LessThanEquals,

        /// <remarks/>
        Begins,

        /// <remarks/>
        Contains,

        /// <remarks/>
        Relative,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class PricingDetailLineItem
    {

        private string lineItemIdField;

        private decimal discountField;

        private decimal discountSumField;

        private decimal listPriceField;

        private decimal quotedPriceField;

        private decimal quotedPriceTotalField;

        private string synchMessageField;

        private string repricingStatusField;

        private string taxRateField;

        private decimal discountRateField;

        private decimal taxField;

        private string lineTypeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LineItemId
        {
            get
            {
                return this.lineItemIdField;
            }
            set
            {
                this.lineItemIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal DiscountSum
        {
            get
            {
                return this.discountSumField;
            }
            set
            {
                this.discountSumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal ListPrice
        {
            get
            {
                return this.listPriceField;
            }
            set
            {
                this.listPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal QuotedPrice
        {
            get
            {
                return this.quotedPriceField;
            }
            set
            {
                this.quotedPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public decimal QuotedPriceTotal
        {
            get
            {
                return this.quotedPriceTotalField;
            }
            set
            {
                this.quotedPriceTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string SynchMessage
        {
            get
            {
                return this.synchMessageField;
            }
            set
            {
                this.synchMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string RepricingStatus
        {
            get
            {
                return this.repricingStatusField;
            }
            set
            {
                this.repricingStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public decimal DiscountRate
        {
            get
            {
                return this.discountRateField;
            }
            set
            {
                this.discountRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public decimal Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string LineType
        {
            get
            {
                return this.lineTypeField;
            }
            set
            {
                this.lineTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class PricingDetail
    {

        private string orderQuoteIdField;

        private decimal discountAmtField;

        private decimal discountPCField;

        private string discountTypeField;

        private decimal grossAmtField;

        private decimal lineItemDiscField;

        private decimal netAmtField;

        private string referenceField;

        private decimal noDiscAmtField;

        private decimal taxField;

        private string pricingListIdField;

        private bool resultField;

        private string errorMessageField;

        private PricingDetailLineItem[] pricingDetailLineItemsField;


        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string OrderQuoteId
        {
            get
            {
                return this.orderQuoteIdField;
            }
            set
            {
                this.orderQuoteIdField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal DiscountAmt
        {
            get
            {
                return this.discountAmtField;
            }
            set
            {
                this.discountAmtField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal DiscountPC
        {
            get
            {
                return this.discountPCField;
            }
            set
            {
                this.discountPCField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DiscountType
        {
            get
            {
                return this.discountTypeField;
            }
            set
            {
                this.discountTypeField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal GrossAmt
        {
            get
            {
                return this.grossAmtField;
            }
            set
            {
                this.grossAmtField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public decimal LineItemDisc
        {
            get
            {
                return this.lineItemDiscField;
            }
            set
            {
                this.lineItemDiscField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public decimal NetAmt
        {
            get
            {
                return this.netAmtField;
            }
            set
            {
                this.netAmtField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public decimal NoDiscAmt
        {
            get
            {
                return this.noDiscAmtField;
            }
            set
            {
                this.noDiscAmtField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public decimal Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string PricingListId
        {
            get
            {
                return this.pricingListIdField;
            }
            set
            {
                this.pricingListIdField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public bool Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayAttribute(Order = 13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ChangeLogEntry")]
        public PricingDetailLineItem[] PricingDetailLineItems
        {
            get
            {
                return this.pricingDetailLineItemsField;
            }
            set
            {
                this.pricingDetailLineItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class LineItemDetail
    {

        private string lineItemIdField;

        private string productFamilyIdField;

        private string productIdField;

        private decimal quantityField;

        private decimal quotedPriceField;

        private string uomIdField;

        private string lineTypeField;

        private bool doNotRepriceField;

        private string locationField;

        private string intForeignIdField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LineItemId
        {
            get
            {
                return this.lineItemIdField;
            }
            set
            {
                this.lineItemIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ProductFamilyId
        {
            get
            {
                return this.productFamilyIdField;
            }
            set
            {
                this.productFamilyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal QuotedPrice
        {
            get
            {
                return this.quotedPriceField;
            }
            set
            {
                this.quotedPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string UomId
        {
            get
            {
                return this.uomIdField;
            }
            set
            {
                this.uomIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string LineType
        {
            get
            {
                return this.lineTypeField;
            }
            set
            {
                this.lineTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool DoNotReprice
        {
            get
            {
                return this.doNotRepriceField;
            }
            set
            {
                this.doNotRepriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string IntForeignId
        {
            get
            {
                return this.intForeignIdField;
            }
            set
            {
                this.intForeignIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class OrderDetailInformation
    {

        private string accountIdField;

        private string orderQuoteIdField;

        private bool isQuoteField;

        private decimal discountAmtField;

        private decimal discountPCField;

        private string discountTypeField;

        private System.DateTime openedField;

        private string statusField;

        private string currencyField;

        private string pricingListIdField;

        private string consigneeField;

        private string salesReprField;

        private string taxRateField;

        private bool doNotRepriceField;

        private string intForeignIdField;
        private string referenceField;

        private LineItemDetail[] lineItemDetailsField;


        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OrderQuoteId
        {
            get
            {
                return this.orderQuoteIdField;
            }
            set
            {
                this.orderQuoteIdField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool IsQuote
        {
            get
            {
                return this.isQuoteField;
            }
            set
            {
                this.isQuoteField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal DiscountAmt
        {
            get
            {
                return this.discountAmtField;
            }
            set
            {
                this.discountAmtField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal DiscountPC
        {
            get
            {
                return this.discountPCField;
            }
            set
            {
                this.discountPCField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string DiscountType
        {
            get
            {
                return this.discountTypeField;
            }
            set
            {
                this.discountTypeField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public System.DateTime Opened
        {
            get
            {
                return this.openedField;
            }
            set
            {
                this.openedField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string PricingListId
        {
            get
            {
                return this.pricingListIdField;
            }
            set
            {
                this.pricingListIdField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string Consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string SalesRepr
        {
            get
            {
                return this.salesReprField;
            }
            set
            {
                this.salesReprField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public bool DoNotReprice
        {
            get
            {
                return this.doNotRepriceField;
            }
            set
            {
                this.doNotRepriceField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string IntForeignId
        {
            get
            {
                return this.intForeignIdField;
            }
            set
            {
                this.intForeignIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayAttribute(Order = 16)]
        public LineItemDetail[] LineItemDetails
        {
            get
            {
                return this.lineItemDetailsField;
            }
            set
            {
                this.lineItemDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class ERPCustomisations
    {

        private string versionField;

        private System.Xml.XmlNode customisationDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.Xml.XmlNode CustomisationData
        {
            get
            {
                return this.customisationDataField;
            }
            set
            {
                this.customisationDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class Configuration
    {

        private string schemaVersionField;

        private string productNameField;

        private string contractVersionField;

        private System.Xml.XmlNode syncSchemaField;

        private System.Xml.XmlNode rTDSchemaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ContractVersion
        {
            get
            {
                return this.contractVersionField;
            }
            set
            {
                this.contractVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.Xml.XmlNode SyncSchema
        {
            get
            {
                return this.syncSchemaField;
            }
            set
            {
                this.syncSchemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.Xml.XmlNode RTDSchema
        {
            get
            {
                return this.rTDSchemaField;
            }
            set
            {
                this.rTDSchemaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class AuthenticationResult
    {

        private PasswordType passwordHandlingField;

        private bool authenticationOnEveryCallField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PasswordType PasswordHandling
        {
            get
            {
                return this.passwordHandlingField;
            }
            set
            {
                this.passwordHandlingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool AuthenticationOnEveryCall
        {
            get
            {
                return this.authenticationOnEveryCallField;
            }
            set
            {
                this.authenticationOnEveryCallField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public enum PasswordType
    {

        /// <remarks/>
        WSSDigest,

        /// <remarks/>
        ClearText,

        /// <remarks/>
        NTAuthentication,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class TransactionResult
    {

        private TransactionStatus statusField;

        private string entityNameField;

        private string messageField;

        private TransactionAction actionField;

        private string cRMIDField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TransactionStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string EntityName
        {
            get
            {
                return this.entityNameField;
            }
            set
            {
                this.entityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public TransactionAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string CRMID
        {
            get
            {
                return this.cRMIDField;
            }
            set
            {
                this.cRMIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public enum TransactionStatus
    {

        /// <remarks/>
        Success,

        /// <remarks/>
        RecoverableError,

        /// <remarks/>
        UnRecoverableError,

        /// <remarks/>
        FatalError,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public enum TransactionAction
    {

        /// <remarks/>
        Created,

        /// <remarks/>
        Updated,

        /// <remarks/>
        Deleted,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class Transaction
    {

        private System.Xml.XmlNode instanceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.Xml.XmlNode Instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class ChangeLogEntry
    {

        private string tokenField;

        private System.Xml.XmlNode instanceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.Xml.XmlNode Instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class ChangeLog
    {

        private bool atEndField;

        private string nextPassTokenField;

        private ChangeLogEntry[] changeLogInstancesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool AtEnd
        {
            get
            {
                return this.atEndField;
            }
            set
            {
                this.atEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string NextPassToken
        {
            get
            {
                return this.nextPassTokenField;
            }
            set
            {
                this.nextPassTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        public ChangeLogEntry[] ChangeLogInstances
        {
            get
            {
                return this.changeLogInstancesField;
            }
            set
            {
                this.changeLogInstancesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    public partial class SessionOpenResult
    {

        private string sessionKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SessionKey
        {
            get
            {
                return this.sessionKeyField;
            }
            set
            {
                this.sessionKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sage.com", IsNullable = false)]
    public partial class CustomisationVersionInfo : System.Web.Services.Protocols.SoapHeader
    {

        private string versionNumberField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string VersionNumber
        {
            get
            {
                return this.versionNumberField;
            }
            set
            {
                this.versionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sage.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sage.com", IsNullable = false)]
    public partial class SchemaVersionInfo : System.Web.Services.Protocols.SoapHeader
    {

        private string versionNumberField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string VersionNumber
        {
            get
            {
                return this.versionNumberField;
            }
            set
            {
                this.versionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }


}
