//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Integration.Northwind.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Integration.Northwind.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountID is mandatory.
        /// </summary>
        internal static string ErrorMessages_AccountIDMadatory {
            get {
                return ResourceManager.GetString("ErrorMessages_AccountIDMadatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field Account Name not set..
        /// </summary>
        internal static string ErrorMessages_AccountNameNotSet {
            get {
                return ResourceManager.GetString("ErrorMessages_AccountNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Linked Account does not exists..
        /// </summary>
        internal static string ErrorMessages_AccountNotFound {
            get {
                return ResourceManager.GetString("ErrorMessages_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given account type was not supported..
        /// </summary>
        internal static string ErrorMessages_AccountTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_AccountTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Customer can Add Orders.
        /// </summary>
        internal static string ErrorMessages_AddOrdersForCustomersOnly {
            get {
                return ResourceManager.GetString("ErrorMessages_AddOrdersForCustomersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one address is supported for Account..
        /// </summary>
        internal static string ErrorMessages_AddressOnlyOneSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_AddressOnlyOneSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given address type was not supported..
        /// </summary>
        internal static string ErrorMessages_AddressTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_AddressTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency not supported.
        /// </summary>
        internal static string ErrorMessages_CurrencyNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_CurrencyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed document type is not supported by this operation..
        /// </summary>
        internal static string ErrorMessages_DocumentTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_DocumentTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Linked Email does not exists..
        /// </summary>
        internal static string ErrorMessages_EmailNotFound {
            get {
                return ResourceManager.GetString("ErrorMessages_EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is no valid field name for the report &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorMessages_InvalidFieldNameForReport {
            get {
                return ResourceManager.GetString("ErrorMessages_InvalidFieldNameForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is no valid ID for &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorMessages_InvalidIDForEntity {
            get {
                return ResourceManager.GetString("ErrorMessages_InvalidIDForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string ErrorMessages_NotImplemented {
            get {
                return ResourceManager.GetString("ErrorMessages_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Customer are supported to receive orders..
        /// </summary>
        internal static string ErrorMessages_OnlyCustomersSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_OnlyCustomersSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented for &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMessages_OperationNotImplementedForEntity {
            get {
                return ResourceManager.GetString("ErrorMessages_OperationNotImplementedForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation tag &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ErrorMessages_OperationTagNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_OperationTagNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order contains one product twice..
        /// </summary>
        internal static string ErrorMessages_OrderContainsProductTwice {
            get {
                return ResourceManager.GetString("ErrorMessages_OrderContainsProductTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two lineitems with the same Product with Id {0} is not supported in ERP..
        /// </summary>
        internal static string ErrorMessages_OrderWithProductTwice {
            get {
                return ResourceManager.GetString("ErrorMessages_OrderWithProductTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given person type was not supported..
        /// </summary>
        internal static string ErrorMessages_PersonTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_PersonTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given phone type was not supported..
        /// </summary>
        internal static string ErrorMessages_PhoneTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_PhoneTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List not supported.
        /// </summary>
        internal static string ErrorMessages_PriceListNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_PriceListNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with Id {0} not found in ERP..
        /// </summary>
        internal static string ErrorMessages_ProductIdNotFound {
            get {
                return ResourceManager.GetString("ErrorMessages_ProductIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId {0} is in the wrong Format..
        /// </summary>
        internal static string ErrorMessages_ProductIdWrongFormat {
            get {
                return ResourceManager.GetString("ErrorMessages_ProductIdWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        internal static string ErrorMessages_ProductNotFound {
            get {
                return ResourceManager.GetString("ErrorMessages_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query field named &apos;{0}&apos; missing..
        /// </summary>
        internal static string ErrorMessages_QueryFieldMissing {
            get {
                return ResourceManager.GetString("ErrorMessages_QueryFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page number is out of range. It must be &gt; 0..
        /// </summary>
        internal static string ErrorMessages_RTDVInvalidPageNumber {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVInvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested number of rows per page is out of range. It must be &gt;= 0..
        /// </summary>
        internal static string ErrorMessages_RTDVInvalidRowsPerPage {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVInvalidRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report &apos;{0}&apos; is not implemented..
        /// </summary>
        internal static string ErrorMessages_RTDVNotImplemented {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report named &apos;{0}&apos; is supported..
        /// </summary>
        internal static string ErrorMessages_RTDVNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL query for the report &apos;{0}&apos; could not be build..
        /// </summary>
        internal static string ErrorMessages_RTDVSQLQueryBuildError {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVSQLQueryBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL query for the report &apos;{0}&apos; could not be build: &apos;{1}&apos; could not be appended to &apos;{2}&apos;.
        /// </summary>
        internal static string ErrorMessages_RTDVSQLQueryBuildError_Debug {
            get {
                return ResourceManager.GetString("ErrorMessages_RTDVSQLQueryBuildError_Debug", resourceCulture);
            }
        }
    }
}
