//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Integration.Northwind.Application.EntityResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CRMSelections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMSelections() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Integration.Northwind.Application.EntityResources.CRMSelections", typeof(CRMSelections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Acc_SubType_Branch {
            get {
                return ResourceManager.GetString("Acc_SubType_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office.
        /// </summary>
        internal static string Acc_SubType_HeadOffice {
            get {
                return ResourceManager.GetString("Acc_SubType_HeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        internal static string Acc_SubType_Independent {
            get {
                return ResourceManager.GetString("Acc_SubType_Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string acc_type_Customer {
            get {
                return ResourceManager.GetString("acc_type_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string acc_type_Supplier {
            get {
                return ResourceManager.GetString("acc_type_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string comp_type_Customer {
            get {
                return ResourceManager.GetString("comp_type_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string comp_type_Supplier {
            get {
                return ResourceManager.GetString("comp_type_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Link_CompAddr_Billing {
            get {
                return ResourceManager.GetString("Link_CompAddr_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Link_CompAddr_Shipping {
            get {
                return ResourceManager.GetString("Link_CompAddr_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string Link_CompEmai_Business {
            get {
                return ResourceManager.GetString("Link_CompEmai_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Link_CompEmai_Sales {
            get {
                return ResourceManager.GetString("Link_CompEmai_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string Link_PersPhon_Business {
            get {
                return ResourceManager.GetString("Link_PersPhon_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Link_PersPhon_Fax {
            get {
                return ResourceManager.GetString("Link_PersPhon_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string orqu_status_Active {
            get {
                return ResourceManager.GetString("orqu_status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string orqu_status_Completed {
            get {
                return ResourceManager.GetString("orqu_status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string orqu_status_Inactive {
            get {
                return ResourceManager.GetString("orqu_status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted.
        /// </summary>
        internal static string orqu_status_Promoted {
            get {
                return ResourceManager.GetString("orqu_status_Promoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string PeLi_Type_Billing {
            get {
                return ResourceManager.GetString("PeLi_Type_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string PeLi_Type_Shipping {
            get {
                return ResourceManager.GetString("PeLi_Type_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        internal static string Pers_Salutation_Dr {
            get {
                return ResourceManager.GetString("Pers_Salutation_Dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        internal static string Pers_Salutation_Miss {
            get {
                return ResourceManager.GetString("Pers_Salutation_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string Pers_Salutation_Mr {
            get {
                return ResourceManager.GetString("Pers_Salutation_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        internal static string Pers_Salutation_Mrs {
            get {
                return ResourceManager.GetString("Pers_Salutation_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        internal static string Pers_Salutation_Ms {
            get {
                return ResourceManager.GetString("Pers_Salutation_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof..
        /// </summary>
        internal static string Pers_Salutation_Prof {
            get {
                return ResourceManager.GetString("Pers_Salutation_Prof", resourceCulture);
            }
        }
    }
}
