//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Integration.Northwind.Application.EntityResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentPropertyCaption {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentPropertyCaption() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Integration.Northwind.Application.EntityResources.DocumentPropertyCaption", typeof(DocumentPropertyCaption).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string account_currencyid {
            get {
                return ResourceManager.GetString("account.currencyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group id.
        /// </summary>
        internal static string account_groupid {
            get {
                return ResourceManager.GetString("account.groupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onhold.
        /// </summary>
        internal static string Account_onhold {
            get {
                return ResourceManager.GetString("Account.onhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtype.
        /// </summary>
        internal static string Account_subtype {
            get {
                return ResourceManager.GetString("Account.subtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string account_type {
            get {
                return ResourceManager.GetString("account.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string address_address1 {
            get {
                return ResourceManager.GetString("address.address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string Address_Address2 {
            get {
                return ResourceManager.GetString("Address.Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address3.
        /// </summary>
        internal static string Address_Address3 {
            get {
                return ResourceManager.GetString("Address.Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address4.
        /// </summary>
        internal static string Address_Address4 {
            get {
                return ResourceManager.GetString("Address.Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressType.
        /// </summary>
        internal static string Address_AddressType {
            get {
                return ResourceManager.GetString("Address.AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Address_City {
            get {
                return ResourceManager.GetString("Address.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Address_Country {
            get {
                return ResourceManager.GetString("Address.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Address_State {
            get {
                return ResourceManager.GetString("Address.State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        internal static string Address_ZipCode {
            get {
                return ResourceManager.GetString("Address.ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Company_CompanyName {
            get {
                return ResourceManager.GetString("Company.CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string Company_CompanyType {
            get {
                return ResourceManager.GetString("Company.CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress.
        /// </summary>
        internal static string Email_EmailAddress {
            get {
                return ResourceManager.GetString("Email.EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossPrice.
        /// </summary>
        internal static string LineItem_CrossPrice {
            get {
                return ResourceManager.GetString("LineItem.CrossPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineItemDiscount.
        /// </summary>
        internal static string LineItem_LineItemDiscount {
            get {
                return ResourceManager.GetString("LineItem.LineItemDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListPrice.
        /// </summary>
        internal static string LineItem_ListPrice {
            get {
                return ResourceManager.GetString("LineItem.ListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID.
        /// </summary>
        internal static string LineItem_ProductID {
            get {
                return ResourceManager.GetString("LineItem.ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string LineItem_Quantity {
            get {
                return ResourceManager.GetString("LineItem.Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotePrice.
        /// </summary>
        internal static string LineItem_QuotePrice {
            get {
                return ResourceManager.GetString("LineItem.QuotePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxAmmount.
        /// </summary>
        internal static string LineItem_TaxAmmount {
            get {
                return ResourceManager.GetString("LineItem.TaxAmmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxRate.
        /// </summary>
        internal static string LineItem_TaxRate {
            get {
                return ResourceManager.GetString("LineItem.TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMID.
        /// </summary>
        internal static string LineItem_UOMID {
            get {
                return ResourceManager.GetString("LineItem.UOMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string NewProduct_Active {
            get {
                return ResourceManager.GetString("NewProduct.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string NewProduct_Code {
            get {
                return ResourceManager.GetString("NewProduct.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStock.
        /// </summary>
        internal static string NewProduct_InStock {
            get {
                return ResourceManager.GetString("NewProduct.InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewProduct_Name {
            get {
                return ResourceManager.GetString("NewProduct.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductFamilyID.
        /// </summary>
        internal static string NewProduct_ProductFamilyID {
            get {
                return ResourceManager.GetString("NewProduct.ProductFamilyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMFamiliyID.
        /// </summary>
        internal static string NewProduct_UOMFamiliyID {
            get {
                return ResourceManager.GetString("NewProduct.UOMFamiliyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountID.
        /// </summary>
        internal static string Orders_AccountID {
            get {
                return ResourceManager.GetString("Orders.AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Orders_Currency {
            get {
                return ResourceManager.GetString("Orders.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDate.
        /// </summary>
        internal static string Orders_DeliveryDate {
            get {
                return ResourceManager.GetString("Orders.DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountAmount.
        /// </summary>
        internal static string Orders_DiscountAmount {
            get {
                return ResourceManager.GetString("Orders.DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountPercentage.
        /// </summary>
        internal static string Orders_DiscountPercentage {
            get {
                return ResourceManager.GetString("Orders.DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        internal static string Orders_Freight {
            get {
                return ResourceManager.GetString("Orders.Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenedDate.
        /// </summary>
        internal static string Orders_OpenedDate {
            get {
                return ResourceManager.GetString("Orders.OpenedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        internal static string Orders_PriceList {
            get {
                return ResourceManager.GetString("Orders.PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Orders_Reference {
            get {
                return ResourceManager.GetString("Orders.Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesRep.
        /// </summary>
        internal static string Orders_SalesRep {
            get {
                return ResourceManager.GetString("Orders.SalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipAddress.
        /// </summary>
        internal static string Orders_ShipAddress {
            get {
                return ResourceManager.GetString("Orders.ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipCity.
        /// </summary>
        internal static string Orders_ShipCity {
            get {
                return ResourceManager.GetString("Orders.ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipCountry.
        /// </summary>
        internal static string Orders_ShipCountry {
            get {
                return ResourceManager.GetString("Orders.ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipName.
        /// </summary>
        internal static string Orders_ShipName {
            get {
                return ResourceManager.GetString("Orders.ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedVia.
        /// </summary>
        internal static string Orders_ShippedVia {
            get {
                return ResourceManager.GetString("Orders.ShippedVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipPostalCode.
        /// </summary>
        internal static string Orders_ShipPostalCode {
            get {
                return ResourceManager.GetString("Orders.ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipRegion.
        /// </summary>
        internal static string Orders_ShipRegion {
            get {
                return ResourceManager.GetString("Orders.ShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Orders_Status {
            get {
                return ResourceManager.GetString("Orders.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalGrossPrice.
        /// </summary>
        internal static string Orders_TotalGrossPrice {
            get {
                return ResourceManager.GetString("Orders.TotalGrossPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalNetPrice.
        /// </summary>
        internal static string Orders_TotalNetPrice {
            get {
                return ResourceManager.GetString("Orders.TotalNetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalQuotedPrice.
        /// </summary>
        internal static string Orders_TotalQuotedPrice {
            get {
                return ResourceManager.GetString("Orders.TotalQuotedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTaxAmount.
        /// </summary>
        internal static string Orders_TotalTaxAmount {
            get {
                return ResourceManager.GetString("Orders.TotalTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string Person_FirstName {
            get {
                return ResourceManager.GetString("Person.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string Person_LastName {
            get {
                return ResourceManager.GetString("Person.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleName.
        /// </summary>
        internal static string Person_MiddleName {
            get {
                return ResourceManager.GetString("Person.MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonType.
        /// </summary>
        internal static string Person_PersonType {
            get {
                return ResourceManager.GetString("Person.PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        internal static string Person_Salutation {
            get {
                return ResourceManager.GetString("Person.Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Person_Suffix {
            get {
                return ResourceManager.GetString("Person.Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Person_Title {
            get {
                return ResourceManager.GetString("Person.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaCode.
        /// </summary>
        internal static string Phone_AreaCode {
            get {
                return ResourceManager.GetString("Phone.AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryCode.
        /// </summary>
        internal static string Phone_CountryCode {
            get {
                return ResourceManager.GetString("Phone.CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        internal static string Phone_PhoneNumber {
            get {
                return ResourceManager.GetString("Phone.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Phone_Type {
            get {
                return ResourceManager.GetString("Phone.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Pricing_Active {
            get {
                return ResourceManager.GetString("Pricing.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyId.
        /// </summary>
        internal static string Pricing_CurrencyId {
            get {
                return ResourceManager.GetString("Pricing.CurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Pricing_Price {
            get {
                return ResourceManager.GetString("Pricing.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceListID.
        /// </summary>
        internal static string Pricing_PriceListID {
            get {
                return ResourceManager.GetString("Pricing.PriceListID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId.
        /// </summary>
        internal static string Pricing_ProductId {
            get {
                return ResourceManager.GetString("Pricing.ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMID.
        /// </summary>
        internal static string Pricing_UOMID {
            get {
                return ResourceManager.GetString("Pricing.UOMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ProductFamily_Description {
            get {
                return ResourceManager.GetString("ProductFamily.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProductFamily_Name {
            get {
                return ResourceManager.GetString("ProductFamily.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string UOM_Active {
            get {
                return ResourceManager.GetString("UOM.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultValue.
        /// </summary>
        internal static string UOM_DefaultValue {
            get {
                return ResourceManager.GetString("UOM.DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UOM_Name {
            get {
                return ResourceManager.GetString("UOM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string UOM_Units {
            get {
                return ResourceManager.GetString("UOM.Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string UOMFamily_Active {
            get {
                return ResourceManager.GetString("UOMFamily.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UOMFamily_Name {
            get {
                return ResourceManager.GetString("UOMFamily.Name", resourceCulture);
            }
        }
    }
}
